services:
  dashboard:
    build: .
    container_name: occupancy-dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./app.py:/app/app.py
      - ./lib:/app/lib
      - ./data:/app/data
    environment:
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped
